### ISSUE TITLE
Add pipeline to build project

### ISSUE THREAD

**Issue by honestit** [honestit/rush#3]
We agree to configure single pipeline based on github actions to build whole project. As a whole project we understand main project module `rush` and all its submodules (like `model`, `services` etc.).

Pipeline should be configured for `main` branch on `push` event.

**Comment by pgancarz** [comment]
@honestit Michał I'm not sure if we can do that (it requires Github pro account which you have as far as I can see) but we would probably like to enable some branch protection rules for our main, staging and production branches. For instance to be able to merge to main at least one approval on PR is required and main-ci workflow green. Also I'm not sure if this is possible in Github, but it would be nice to allow merging PR that can be merged using fast forward strategy. It will force everyone to merge/rebase his branch with master before merging to main, so we would avoid someone wiping out someone else's changes.  Something like that. We can discuss it later.

@all
I've added some basic actions workflow which will just run build on the whole project on `push` or `pull request` to `main` which I think is enough right now. I'm not sure do we really need it build on push to main, since we'd probably like to allow to merge to main only if build on PR succeeded. At this moment I'm not sure if want for instance to run the whole build including all integration tests for PR or maybe we would like to run them cyclic (every Monday)  or only when we merging something to `staging` or `produciton`

FYI: i've accidentally fixed #2 and #3 tasks on the same branch... but I decided that it's not a big deal since the last commit actually adds the workflow for pull request and this way you can actually see that the gradle configuration works.
